; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @src(i32 %0) {
; CHECK-LABEL: define i32 @src(
; CHECK-SAME: i32 [[TMP0:%.*]]) {
; CHECK-NEXT:    [[V0:%.*]] = and i32 [[TMP0]], -4
; CHECK-NEXT:    [[V1:%.*]] = add i32 [[V0]], -1
; CHECK-NEXT:    [[V2:%.*]] = and i32 [[V1]], -4
; CHECK-NEXT:    [[V3:%.*]] = add i32 [[V2]], 4
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v0 = and i32 %0, -4
  %v1 = add i32 %v0, -1
  %v2 = and i32 %v1, -4
  %v3 = add i32 %v2, 4
  ret i32 %v3
}
